powdata<-read.delim("household_power_consumption.txt",header=TRUE,sep=";",na.strings="?",stringsAsFactors=FALSE)
powdata$Date<-as.Date(powdata$Date,format="%d/%m/%Y")
powdata$DateTime<-paste(powdata$Date,powdata$Time)
powdata$DateTime<-strptime(powdata$DateTime,format="%Y-%m-%d %H:%M:%S")
subpowdata<-powdata[powdata$Date>=as.Date("2007-02-01")&powdata$Date<as.Date("2007-02-03"),]
png("plot4.png",width=480,height=480)
par(mfrow=c(2,2))
par(mar=c(5,4,3,2))
plot(subpowdata$DateTime,subpowdata$Global_active_power,type="l",xlab="",ylab="Global Active Power")
plot(subpowdata$DateTime,subpowdata$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(subpowdata$DateTime,subpowdata$Sub_metering_1,type="n",xlab="",ylab="Energy sub metering")
points(subpowdata$DateTime,subpowdata$Sub_metering_1,type="l",col="black")
points(subpowdata$DateTime,subpowdata$Sub_metering_2,type="l",col="red")
points(subpowdata$DateTime,subpowdata$Sub_metering_3,type="l",col="blue")
legend("topright",inset=0.01,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,box.lty=0)
plot(subpowdata$DateTime,subpowdata$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()